### ISSUE TITLE
Implement Terraform login protocol

### ISSUE THREAD

**Issue by jcanizalez** [AzBuilder/terrakube-server#20]
In order to enable authentication in the open registry and allows to use  `terraform login azbserver.com`  is required to implement  Terraform login protocol

1.  Modify  /.well-known/terraform.json to include a new property with static values as follows:

```
{
  "login.v1": {
    "client": "terraform-cli",
    "grant_types": ["authz_code"],
    "authz": "/oauth/authorization",
    "token": "/oauth/token",
    "ports": [10000, 10010],
  }
}
```

2. Create OAuth 2.0 endpoints:
     a. Using **authz** value from step 1, create an [authorization endpoint](https://tools.ietf.org/html/rfc6749#section-3.1) Example: https://azbserver.com/oauth/authorization   
    b. Using **token** value from step 1, create a [token endpoint](https://tools.ietf.org/html/rfc6749#section-3.2) Example: https://azbserver.com/oauth/token

**Comment by alfespa17** [comment]
Terraform login protocol is fully supported from version 1.6.3
