### ISSUE TITLE
Error downloading Terraform modules

### ISSUE THREAD

**Issue by SalvoRusso8** [AzBuilder/terrakube-server#200]
Hi all.

We installed Terrakube in a private Kubernetes cluster using the Helm Chart, but we are having issues using terraform modules.

Since we use snippet of code like (for example):

```
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "my-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = true

  tags = {
    Terraform = "true"
    Environment = "dev"
  }
}
```

we receive the following error in the executor pod logs:

```
Error: Failed to download module
Could not download module "vpc" (onboarding.tf:63) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v3.14.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v3.14.0': git must be available and on the PATH.
``` 

In the Executor pod the `git` command is not installed.

My problem seems related to this issue: https://github.com/AzBuilder/terrakube-executor/issues/6 but I do not understand what is wrong with my terraform plan.

Can you help me? 
Thanks

**Comment by SalvoRusso8** [comment]
Hi @alfespa17 and thanks for your answer.

As you can see in the snippet of code that I've sent in the issue, we are already using your proposed syntax, but it does not fix the problem.

**Comment by alfespa17** [comment]
Hello @SalvoRusso8 

I was able to reproduce your issue:
![image](https://user-images.githubusercontent.com/4461895/172464084-b9bf99bc-2cc0-4a33-b5be-8bda1ca8c804.png)

The main problem is that when terraform cli is downloading the module from the terraform registry inside the executor the X-Terraform-Get is returning the git connection.
``
https://registry.terraform.io/v1/modules/terraform-aws-modules/vpc/aws/3.4.0/download
``
![image](https://user-images.githubusercontent.com/4461895/172463484-1b16afca-abcd-46c0-8ce0-2696b8ee7cd1.png)

I am using ***"mvn spring-boot:build-image"*** to create the all the docker image for terrakube so I will double check how to add git dependency, so we can fix this issue.

**Comment by alfespa17** [comment]
Hello @SalvoRusso8 

I did some small changes, if you upgrade to executor version 2.4.2, it should work, you can check this PR #202

**Comment by SalvoRusso8** [comment]
I can confirm that actually it works! Thanks.

Now we will move into using modules in private repositories. I will open a new issue in case of problems.
