### ISSUE TITLE
"Not Authorized" for module in private repository in GitHub

### ISSUE THREAD

**Issue by SalvoRusso8** [AzBuilder/terrakube-server#203]
Hi.

We are trying to use a module in a private repository in GitHub.
As you can see in the screenshot, the version list is correctly working, but in the registry pod's logs we see
```
 o.a.registry.service.git.GitServiceImpl  : https://github.com/***/terraform-aws-***.git: not authorized
```
We tried a terraform plan in Terrakube using a repository without modules in the same GitHub organization and it works without problems, but we are not able to let Terrakube get the module.

![Schermata 2022-06-08 alle 18 00 02](https://user-images.githubusercontent.com/61883800/172664022-f3f4a02d-61fc-4fc2-a8c2-b4f7ea03714e.png)

Are we doing anything wrong in the configuration?

Also, compared to Terraform Cloud, in Terrakube there is no possibility to configure an SSH key to let the git cli access other repositories (with the goal to use modules without having to use the registry). We think it can be useful to have this feature in a future release.

Thanks

**Comment by alfespa17** [comment]
Hello @SalvoRusso8 

API 2.4.3 should fix this issue, and you should be able to see the README.md information

Regards.
